version: '{branch}-{build}'
build: off
environment:
  global:
    COVERALLS_REPO_TOKEN:
      secure: 1FnQ1slZatdVqT63JCuf/ALH3jviE6zwCwmiE7JSV8MD2M5KhktvLOgmhbwwXp4+
    TWINE_PASSWORD:
      secure: fDwCnDhQiptm9a4ZcFpgyQ==
    TWINE_USERNAME: ionel
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd %PYTHON_HOME%\Scripts\tox

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
on_success:
  - |
    ECHO ON
    SETLOCAL EnableDelayedExpansion
    IF DEFINED WHEEL_PATH (
      %PYTHON_HOME%\Scripts\twine check %WHEEL_PATH%/*.whl
      %PYTHON_HOME%\Scripts\twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing %WHEEL_PATH%/*.whl
    ) ELSE (
      ECHO No wheels to upload.
    )

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
